CURRENTSHELL=zsh

COMMONPROFILE=${HOME}/dotfiles/common/profile

test -r ${COMMONPROFILE} && . ${COMMONPROFILE}

LOCALPROFILE=${HOME}/dotfiles/local/profile

test -r ${LOCALPROFILE} && . ${LOCALPROFILE}