CURRENTSHELL=bash

COMMONPROFILE=${HOME}/dotfiles/common/profile

test -r ${COMMONPROFILE} && . ${COMMONPROFILE}

LOCALPROFILE=${HOME}/dotfiles/local/profile

test -r ${LOCALPROFILE} && . ${LOCALPROFILE}

test -r ${HOME}/.bashrc && . ${HOME}/.bashrc